### ISSUE TITLE
oref doesn't respect editor window layout

### ISSUE THREAD

**Issue by jvasile** [OpenTechStrategies/ots-tools#12]
Sometimes it is convenient to display notes in one window and the doc in the other. When following a ref, if the window is split in 2 or more, oref should (perhaps optionally) open that ref in the other window.  If that other window is already displaying the file oref is about to jump to, it should definitely just use that window.

**Comment by kfogel** [comment]
This is now tracked [here](https://code.librehq.com/ots/ots-tools/-/issues/1).
