### ISSUE TITLE
opass: if git-svn prompts for a passphrase, opass will hang

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/ots-tools#14]
If the underlying invocation fo `git svn` prompts for a passphrase, then `opass` will just hang.

Most operations start with `git svn rebase` (that is, `do_pass_thing()` calls `do_git_svn_thing("rebase")` before doing the main operation).  But if the Subversion repository passphrase isn't cached somehow, then `git svn rebase` will just prompt for it.  Unfortunately, `opass` doesn't detect that this is happening, nor do anything to prevent it from happening.  It just sits there until the user gives up and interrupts `opass` (and, presumably, curses in mystified frustration).

**Comment by gtback** [comment]
I can attest to the "mystified frustration" of this behavior. That's part of why I added the `verbose` mode (#16).

**Comment by kfogel** [comment]
@gtback, may I put this on your plate?

The desired behavior, I think, is for `opass` to detect if the subprocess is prompting for user input (namely, for the password), and handle that appropriately -- get the password from the user in a password-y way, and send it along to the `pass git-svn ...` subprocess.  This may involve changing `opass` to use something other than `subprocess.run()` to invoke `pass`.

(I've tested that, e.g., `pass git-svn rebase` does indeed prompt for a password if no cached password is available or if the cached password is wrong.)

**Comment by gtback** [comment]
Yep, I'll take a look at this.

**Comment by gtback** [comment]
> This may involve changing `opass` to use something other than `subprocess.run()` to invoke `pass`.

I've spent some time looking into this, and there doesn't seem to be a way to do this (that I've found) using the `subprocess.run` interface. I think I'll have to drop down and use `subprocess.Popen` directly. 

Before I make too many changes, I want to make sure I understand [this comment](https://github.com/OpenTechStrategies/ots-tools/blob/f28f20645214e7e68833902529903e34d9c661f8/opass#L334-L341) correctly.

> We filter some lines out because they're common and
> carry no useful information.  Everything else we print,
> but always to stderr, whether it came from stdout or
> stderr.  That's because the output here isn't the main
> purpose of opass, but is just a side effect of the
> surrounding toolchain, and having noise on stdout was
> affecting scripts that use opass to automatically fetch
> secrets for use with, e.g., ansible.

I'm assuming this is just true for `do_git_svn_thing()` because the same logic isn't replicated in `do_pass_thing`. That is, when we launch a `pass` subprocess, we want to correctly mirror stdout and stderr, but any output from `git-svn` (to either stdout or stderr) will get written to `opass`'s stderr. For scripting cases, we want to be sure that the stdout has only the values from `pass` (typically `pass show`) Is this correct, @kfogel ?

**Comment by kfogel** [comment]
Yes, I think that's correct.

(I was wondering whether we should also print to stderr instead of stdout in your recent [PR #16 to add a verbose mode](https://github.com/OpenTechStrategies/ots-tools/pull/16).  I decided I didn't have a clear opinion; I'm just mentioning it here as a possibility in case you do.)

**Comment by gtback** [comment]
> (I was wondering whether we should also print to stderr instead of stdout in your recent [PR #16 to add a verbose mode](https://github.com/OpenTechStrategies/ots-tools/pull/16). I decided I didn't have a clear opinion; I'm just mentioning it here as a possibility in case you do.)

Yes, I think it makes sense to print those to stderr as well. Even though I don't expect `--verbose` to be used from scripting contexts, its a good consistent rule "the only output `opass` will print to `stdout` is the output from `pass` itself". I'll update that as part of this issue.

**Comment by slifty** [comment]
Wanted to bump this issue -- I face it every time I use opass :(

**Comment by kfogel** [comment]
Pinging @gtback re above :-).

**Comment by gtback** [comment]
Yep, I saw this. Sorry for not responding. I've been very busy lately but will try to get this done this week.

**Comment by kfogel** [comment]
Thanks, @gtback.  We understand it's all as you have opportunity/time -- no worries at all.

**Comment by kfogel** [comment]
Closing here; this is now ticketed as [issue number 3](https://code.librehq.com/ots/ots-tools/-/issues/3) in the new repository.
