### ISSUE TITLE
Is it possible to specify your git-svn username when calling opass?

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/ots-tools#19]
My local username isn't the same as my ots / svn username, which I think is part of why I face issues with #14

Is there a way to tell opass which user to use when invoking git-svn?

I know I can configure svn to use a different user based on host, though I could see value in being able to specify on a per-command basis as well.  Either way maybe worth updating the documentation to instruct users the opass-preferred method of specifying svn username.

**Comment by kfogel** [comment]
I've started work on a `--username` option, in branch [19-specify-git-svn-username](https://github.com/OpenTechStrategies/ots-tools/tree/19-specify-git-svn-username) (see commit ba96439ce52e).  It's doable, but a bit more complex than I realized, because the username has to get sent through to the [pass-git-svn](https://github.com/opentechstrategies/pass-git-svn) extension (i.e., `git-svn.bash`), which would then send it through to `git-svn`.  I don't think (?) that extension yet knows how to do that, so this is a two-part change.

Your comment implies that you might have a workaround you're currently using?  If so, what is it?

**Comment by slifty** [comment]
> Your comment implies that you might have a workaround you're currently using? If so, what is it?

My immediate answer to this was "great question... magic? I think maybe my computer has developed intuition and just knows these things?"

But unfortunately I found the answer.

[I had specified the username in my `~/.subversion/servers` file](https://github.com/slifty/dotfiles/blob/47f0aaeca176445b483395f4467d073c86188205/ots/install.sh#L1-L3):

```
[groups]
ots = svn.opentechstrategies.com

[global]

[ots]
username = dan
```

Probably not useful but in case it is, [this](https://github.com/slifty/dotfiles/commit/143b54ede1b65b38c3624e80046e31960c24c172) is what I use to set up OTS development.

**Comment by jvasile** [comment]
In what repo does `git-svn.bash` live?  It looks like I wrote that code, but... I have no memory of it.

**Comment by kfogel** [comment]
> In what repo does `git-svn.bash` live? It looks like I wrote that code, but... I have no memory of it.

It's linked to in my comment above :-).  https://github.com/opentechstrategies/pass-git-svn  (and yes, you wrote the code, as far as I know!)

**Comment by slifty** [comment]
Is that repo the right place to create this issue?  If so I can open one there (and maybe take a moment to try to add the feature some time later)

**Comment by kfogel** [comment]
Well, I think both repositories need a ticket: `pass-git-svn` needs a ticket to take a username and pass it along to `git-svn`, and `opass` needs a ticket to take a username and pass it along to `pass-git-svn`.

I've just filed [ticket #1](https://code.librehq.com/ots/pass-git-svn/-/issues/1) in `pass-git-svn` for this, cross-linking back with this ticket.

@slifty feel free to make the fix, yeah!  But no obligation -- the responsibility is no more yours than anyone else's.

**Comment by kfogel** [comment]
Closing here; this is now ticketed as [issue number 4](https://code.librehq.com/ots/ots-tools/-/issues/4) in the new repository.
