### ISSUE TITLE
Suggestion: move safergrep to this repo

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/ots-tools#8]
Since [safergrep](http://svn.red-bean.com/repos/kfogel/trunk/bin/safergrep) depends on [no-longer-than](https://github.com/OpenTechStrategies/ots-tools/blob/master/no-longer-than), which is now in this repo, why not move safergrep here too?

**Comment by kfogel** [comment]
Done :-).

**Comment by cecilia-donnelly** [comment]
Thanks @kfogel! (Obviously I was using these recently, so also thanks for writing/publishing them. 🙂  )
